# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Show tasks
    cmds:
      - task -a
    silent: true

  init:env:
    desc: Setup dev env
    cmds:
      - touch .env
      - echo "DEV=True" >> .env

  init:py:
    desc: Setup python environment
    cmds:
      - uv pip compile requirements.in -o requirements.txt
      - sleep 1
      - uv pip install -r requirements.txt

  init:poly:
    desc: Create workspaces
    cmds:
      - mkdir go_work
      - mkdir elixir_work
      - mkdir julia_work
      - mkdir jsts_work
      - mkdir rust_work
      - mkdir other_work
      - mkdir scripts

  new:go:mock:
    desc: Make go app to generate mock directory
    cmds:
      - mkdir -p go_work/mockgen
      - cd go_work/mockgen && go mod init polycrypt/mockgen
      - cd go_work/mockgen && go get github.com/brianvoe/gofakeit/v6@latest
      - cd go_work && go work init ./mockgen
      - touch go_work/mockgen/main.go
